config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "up" => "rails/health#show", as: :rails_health_check

  resources :tasks
  resources :lists

  root to:  'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks, dependent: :destroy
    validates :title, presence: true
end

app/models/task.rb
  class Task < ApplicationRecord
    belongs_to :list
    validates :title, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :set_list
    after_action :set_session

    def new
        @list = List.create(title: 'New list', description: 'description')

        if @list.save
            flash[:success] = 'List created successfully!'
            session[:reload_root] = true
            session[:flash_message] = flash.to_hash
        else
            flash[:error]  = 'Failed to create list.'
        end
    
        redirect_to root_path
    end

    def destroy
        @list = List.find(params[:id])
        @list.destroy

        if @list.destroy
            flash[:success] = 'List deleted successfully!'
        else
            flash[:error]  = 'Failed to delete list.'
        end
        
        session[:reload_root] = true
        session[:flash_message] = flash.to_hash
        redirect_to root_path
    end

    def update
        @list = List.find(params[:id])
        if @list.update(list_params)
            render json: { success: true, message: 'List updated successfully' }
        else
            render json: { success: false, message: 'Error updating list' }
        end
    end
    
    private
    def list_params
        params.require(:list).permit(:title, :description)
    end 

    def set_list
        @lists = List.includes(:tasks).all
    end

    def set_session
        session[:reload_root] = true
        session[:flash_message] = flash.to_hash
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @lists = List.includes(:tasks).all
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    after_action :set_session
 
    def create
        @task = Task.new(task_params)

        if @task.save
            flash[:success] = 'Task created successfully!'
        else
            flash[:error] = 'Failed to create task.'
        end
        
        redirect_to root_path
    end
  
    def destroy
        @task = Task.find(params[:id])
        
        if @task.destroy
            flash[:success] = 'Task deleted successfully!'
        else
            flash[:error] = 'Failed to delete task.'
        end
        
        redirect_to root_path
    end

    def update
        @task = Task.find(params[:id])
        
        if @task.update(task_params)
            flash[:success] = 'Task updated successfully!'
        else
            flash[:error] = 'Failed to update task.'
        end

        redirect_to root_path
    end
    
    private

    def task_params
        params.require(:task).permit(:title, :note, :completed, :list_id)
    end

    def set_session
        session[:reload_root] = true
        session[:flash_message] = flash.to_hash
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if session[:reload_root] %>
      <script>
        // Force reload
        if (window.location.pathname === '<%= root_path %>') {
          location.reload();
        }
      </script>

      <% session.delete(:reload_root) %>
      <% flash.replace(session.delete(:flash_message) || {}) %>
    <% end %>
    
    <div class="div-header">
          <h1>To-Do Lists</h1>
          <%= link_to 'New List', new_list_path, class: 'btn btn-primary' %>
    </div>

    <%= yield %>

    <div id="divFlashMessage">
      <p id="flashMessage"><%= flash[:success] || flash[:error] %></p>
    </div>
    
    <div id="myModal" class="modal-task">
      <div class="modal-content">
        <span class="close" id="closeModalBtn">&times;</span>
        <h2 class="modal-title">New Task</h2>
        <%= form_with(model: Task, url: '', remote: true, id:'editCreateTask') do |form| %>
          <%= form.label :title %>
          <div class="field">
            <p>
              <span class="input">
              <%= form.text_field :title, id: 'modalTaskTitle', maxlength:'50', size:'auto'%>
                <span></span>	
              </span>
            </p>
          </div>
          <div class="field">
          <%= form.label :note %>
          <div class="field">
            <p>
            <span class="input">
              <%= form.text_area :note, id: 'modalTaskNote',  maxlength:'50' %>
              <span></span>	
            </span>
          </p>
          </div>
          <%= form.hidden_field :completed, value: 'false', id: 'modalTaskCompleted' %>
          <%= form.hidden_field :list_id, value: '', id: 'taskListId' %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="actions">
          <%= form.submit 'Create', class: 'btn modal-btn', id: 'modalBtn' %>
          </div>
        <% end %>
      </div>
    </div>

  </body>
</html>

app/views/lists/_show.html.erb
<div class="head-div-list">
  <%= form_with(model: list, 
                method: :delete, 
                data: { confirm: 'Você tem certeza?' }) do |form| %>
    <%= form.button nil, 
      class: "btn-delete-list btn btn-primary", 
      id: "deleteBtn#{list.id}" do
    %>
      <i class="fa-solid fa-xmark"></i>
    <% end %>
  <% end %>
  <div class="group-head-div">
      <p id="listTitle<%= list.id %>" class='title'><%= list.title %></p>
      
      <button class="edit-list-btn btn btn-primary" 
              data-list-id="<%= list.id %>" 
              data-edit-mode="edit"
      >
        <i class="fa-regular fa-pen-to-square"></i>
        <span class="button-text-<%= list.id %>"></span>
      </button>
  </div>
  <p class="text-info" id="listNote<%= list.id %>"><%= list.description %></p>
</div>
<hr>
<% list.tasks.each do |task| %>
  <%= render partial: 'tasks/show', locals: { task: task } %>
<% end %>

<button class="openModalBtn btn" data-list-id="<%= list.id %>">Add task</button>

app/views/pages/home.html.erb
<container>
  <% if @lists.empty? %>
    <span class="text-warning">No lists yet!</span>
  <% else %>
      <% @lists.each do |list| %>
        <div class="list-item">
          <%= render partial: 'lists/show', locals: { list: list } %>
        </div>
      <% end %>
  <% end %>
</container>

app/views/tasks/_show.html.erb
<div class="task-div task-item-<%= task.id %>">
    <div class="group-head-div">
    <button class="edit-task-btn task-title-<%= task.id %>" data-task-id="<%= task.id %>">
        <%= task.title %>
    </button>
        <%= form_with(model: task, method: :delete, data: { confirm: 'Você tem certeza?' }) do |form| %>
            <%= form.button nil, class: "btn-delete-task btn btn-primary" do %>
                <i class="fa-solid fa-trash-can-arrow-up"></i>            
            <% end %>
        <% end %>
    </div>

    <div class="group-head-div note">
        <p><%= task.note %></p>
        <div class="task-switch">
            <%= form_with(model: task, method: :patch, url: task_path(task), remote: true) do |form| %>
                <label class="switch">
                    <%= form.check_box :completed, 
                        class: "switch-input task-checkbox", 
                        onchange: "this.form.submit();"
                    %>
                    <span class="slider round"></span>
                </label>
            <% end %>
        </div>

    </div>
</div>